### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by albttx** [tyranron/go-sizeof-tip#2]
Hello ! Thank you for the website: http://golang-sizeof.tips/

Just to notice you that the website is down with a 502 error.

Will you fix it ?

Thanks

**Comment by tyranron** [comment]
@ale-batt oooff... totally forgot about that site 😵

Is anyone really use it, btw?

**Comment by tyranron** [comment]
@ale-batt up again

**Comment by albttx** [comment]
Yes i do :) 

Nice thank you 👍
